# -*- coding: utf-8 -*-
"""IPL_Pratyasha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1huo75FNJUhwVkdjY2eiVcz6h-obOc1oH
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/ipl dataset.csv")
print(df)

df.head()

df.tail()

df.shape

df.columns

df.info()

df.describe()

df['date'].max()

df['date'].describe()

df.dtypes.value_counts()

df.sort_values(by='season')

df.isnull().sum()

df.nunique()

sns.pairplot(df,hue="winner")

sns.jointplot(x='date',y='season',data=df,kind='reg')

sns.barplot(x='season',y='city',data=df)

sns.displot(x='city',data=df)

corr=df[['id','season']].corr()
sns.heatmap(corr)

sns.histplot(data=df,x='season')

sns.scatterplot(x='season',y='city',data=df,hue='date')

