# -*- coding: utf-8 -*-
"""tips.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_AEmGA8GGaeP7ivJIk4AFednXXRuxOh
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/seaborn.csv")
print(df)

df.head()

df.info()

df.shape

df.columns

df.isnull()

df.isnull().sum()

df.nunique

corr=df[['tip','total_bill']].corr()
sns.heatmap(corr)

sns.displot(x='day',data=df)

sns.pairplot(df,hue="tip")

sns.barplot(x='day',y='tip',data=df)

df1=df.drop(['day'],axis='columns')
print(df1)

df['tip'].hist(bins=20)

df[df.total_bill>10.34]

df[df.tip>5.54]#who gave tips more than 5.54