# -*- coding: utf-8 -*-
"""World Cup Matches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBcTMSpYKZOIjF6s-fiei27k2gyThTDO
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("/content/WorldCupMatches (2).csv")
print(df)

df.shape

df.columns

df[2:5]

df.info()

df.describe()

df['Away Team Goals'].mean()

df.isnull() #show the missing value

df.isnull().sum() #count the missing value

df['Attendance'].fillna(df['Attendance'].mean(),inplace=True)#missing value clean
df.isnull().sum()

sns.pairplot(df,hue="Attendance")

sns.jointplot(x='Attendance',y='Year',data=df,kind='reg')

sns.barplot(x='Year',y='City',data=df)

sns.displot(x='Attendance',data=df)

corr=df[['Attendance','Year',]].corr()
sns.heatmap(corr)

sns.scatterplot(x='Year',y='City',data=df)

sns.histplot(data=df,x='Year')

sns.boxplot(df=['Date and Time'])